package qsptools;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.Map;
import java.util.logging.Level;
import javax.swing.AbstractAction;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import hmi.log.QspLogger;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author pseudo555
 */
public class MainFrame extends JFrame {
        
    private static final String VERSION = "QspTools v0.0.8 - xx/xx/2015";
    public static final String CONSOLE = "F12";

    /**
     * Creates new form MainFrame
     */
    public MainFrame(String[] args) {
        initComponents();
        setTitle(VERSION);
        jLabel1.setText("<html><h1>"+VERSION+"</h1></html>");
        
        if(args.length > 0){
            translatorMainPanel2.setMode("multi".equalsIgnoreCase(args[0]));
        }
        
        final QspLogger logger = QspLogger.getInstance(this);        
        ((JPanel)getContentPane()).getActionMap().put(CONSOLE, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // NPE to Fix !!!
                logger.setVisible(! logger.isVisible());
                if(logger.isVisible()){
                    logger.updateText();
                }
            }
        });
        ((JPanel)getContentPane()).getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0), CONSOLE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        translatorMainPanel1 = new qsptools.translator.TranslatorMainPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        translatorPanel = new javax.swing.JPanel();
        translatorMainPanel2 = new qsptools.translator.TranslatorMainPanel();
        passwordPanel = new javax.swing.JPanel();
        passwordMainPanel1 = new qsptools.password.PasswordMainPanel();
        changePanel = new javax.swing.JPanel();
        changeLogPanel1 = new hmi.changelog.ChangeLogPanel();

        javax.swing.GroupLayout translatorMainPanel1Layout = new javax.swing.GroupLayout(translatorMainPanel1);
        translatorMainPanel1.setLayout(translatorMainPanel1Layout);
        translatorMainPanel1Layout.setHorizontalGroup(
            translatorMainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        translatorMainPanel1Layout.setVerticalGroup(
            translatorMainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QspTools version - date");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        translatorPanel.setLayout(new java.awt.BorderLayout());
        translatorPanel.add(translatorMainPanel2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Translate", translatorPanel);

        passwordPanel.setLayout(new java.awt.BorderLayout());
        passwordPanel.add(passwordMainPanel1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Password", passwordPanel);

        changePanel.setLayout(new java.awt.BorderLayout());
        changePanel.add(changeLogPanel1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Changelog", changePanel);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            QspLogger.log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                QspLogger.info("Starting "+new Date());
                new MainFrame(args).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private hmi.changelog.ChangeLogPanel changeLogPanel1;
    private javax.swing.JPanel changePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private qsptools.password.PasswordMainPanel passwordMainPanel1;
    private javax.swing.JPanel passwordPanel;
    private qsptools.translator.TranslatorMainPanel translatorMainPanel1;
    private qsptools.translator.TranslatorMainPanel translatorMainPanel2;
    private javax.swing.JPanel translatorPanel;
    // End of variables declaration//GEN-END:variables
}
