package qsptools.password;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author pseudo555
 */
public class PasswordMainPanel extends javax.swing.JPanel {
    
    private static final String INPUT = "input";
    private static final String RESULT = "result";

    private final InputFilePanel inputPanel;
    private final ResultPanel resultPanel;
    private final CardLayout cardLayout = new CardLayout();
    /**
     * Creates new form PasswordMainPanel
     */
    public PasswordMainPanel() {
        
        inputPanel = new InputFilePanel(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                resultPanel.setFile( inputPanel.getFile());
                cardLayout.show(PasswordMainPanel.this, RESULT);
            }
        });
        resultPanel = new ResultPanel(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                inputPanel.reset();
                cardLayout.show(PasswordMainPanel.this, INPUT);
            }
        });
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        setLayout(cardLayout);
        add(resultPanel, RESULT);
        add(inputPanel, INPUT);
        
        cardLayout.show(this, INPUT);
    }
}
